name: Cypress
on:
  push:
    branches-ignore:
      - renovate/**
  pull_request:

jobs:
  cypress-run:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        browsers: [chrome, firefox]
        languages: [english, chinese, espanol]

    env:
      BUILD_LANG: ${{ matrix.languages }}

      ENGLISH_GHOST_API_URL: ${{ secrets.CI_ENGLISH_GHOST_API_URL }}
      ENGLISH_GHOST_API_VERSION: ${{ secrets.CI_ENGLISH_GHOST_API_VERSION }}
      ENGLISH_GHOST_CONTENT_API_KEY: ${{ secrets.CI_ENGLISH_GHOST_CONTENT_API_KEY }}

      CHINESE_GHOST_API_URL: ${{ secrets.CI_CHINESE_GHOST_API_URL }}
      CHINESE_GHOST_API_VERSION: ${{ secrets.CI_CHINESE_GHOST_API_VERSION }}
      CHINESE_GHOST_CONTENT_API_KEY: ${{ secrets.CI_CHINESE_GHOST_CONTENT_API_KEY }}

      ESPANOL_GHOST_API_URL: ${{ secrets.CI_ESPANOL_GHOST_API_URL }}
      ESPANOL_GHOST_API_VERSION: ${{ secrets.CI_ESPANOL_GHOST_API_VERSION }}
      ESPANOL_GHOST_CONTENT_API_KEY: ${{ secrets.CI_ESPANOL_GHOST_CONTENT_API_KEY }}

      POSTS_PER_PAGE: ${{ secrets.POSTS_PER_PAGE }}

      SITE_DOMAIN: localhost:8080

      LOCALE_FOR_UI: ${{ matrix.languages }}
      LOCALE_FOR_GHOST: ${{ matrix.languages }}

    steps:
      - name: Checkout source files
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Start Ghost containers
        run: docker-compose -f 'docker-config/ghost/docker-compose.yml' up -d

      - name: Start CI server and run Cypress
        uses: cypress-io/github-action@v2
        with:
          start: npm run start:ci:${{ matrix.languages }}
          wait-on: http://localhost:8080
          wait-on-timeout: 1200
          browser: ${{ matrix.browsers }}
          headless: true
          spec: cypress/integration/${{ matrix.languages }}/**/*

      - name: Stop Ghost containers
        run: docker-compose -f 'docker-config/ghost/docker-compose.yml' down
